Fixed deserialization when serialVersionUID mismatches.
I noticed this when I built the project on AdoptOpenJDK. One of our
tests revealed that some of our result classes (written in Scala) have
different serialVersionUIDs, probably differing based on the JVM
implementation details.

```
[ERROR] testScatterPlotVisualizationComponentLoading(org.datacleaner.test.scenario.OpenAnalysisResultTest)
Time elapsed: 0.02 s  <<< ERROR!
java.lang.IllegalStateException: java.io.InvalidClassException:
org.datacleaner.visualization.ScatterGroup$$anonfun$1; local class
incompatible: stream classdesc serialVersionUID = -4484196027050979344,
local class serialVersionUID = 0
        at org.datacleaner.test.scenario.OpenAnalysisResultTest.testScatterPlotVisualizationComponentLoading(OpenAnalysisResultTest.java:94)
Caused by: java.io.InvalidClassException:
org.datacleaner.visualization.ScatterGroup$$anonfun$1; local class
incompatible: stream classdesc serialVersionUID = -4484196027050979344,
local class serialVersionUID = 0
        at org.datacleaner.test.scenario.OpenAnalysisResultTest.testScatterPlotVisualizationComponentLoading(OpenAnalysisResultTest.java:94)
```

This fixes the situation, based on advice from StackOverflow thread on a
similar issue:
https://stackoverflow.com/questions/1816559/make-java-runtime-ignore-serialversionuids